version: '3.8'
name: 'ktpm'
services:
  db:
    image: mcr.microsoft.com/mssql/server:latest
    ports:
      - 1433:1433
    environment:
      - MSSQL_SA_PASSWORD=ktpm@123
      - ACCEPT_EULA=Y

    volumes:
      - ./transfer/:/var/opt/transfer/